questions = [
    {
        "eng_question": "We have two types of connection (Main Wire and wall outlet)",
        "arabic_question": "وجد لدينا نوعين من التوصيل (Main Wire and wall outlet)",
        "options": ["True", "False"],
        "correct_answer": "True",
        "day": "Day 03 - Network fundamentals",
    },
    {
        "eng_question": "In CPE configuration 'VDSL' Parameters XDSL Transfer Mode Should be ?",
        "arabic_question": "ال 'VDSL' Parameters CDSL Transfer Mode في اعدادات الروتر يجب ان تكون ",
        "options": ["PPPOE", "PPP", "PTM"],
        "correct_answer": "PTM",
        "day": "Day 03 - Network fundamentals",
    },
    {
        "eng_question": "Which of the below is the responsible for translating any domain name into IP and Vice Versa",
        "arabic_question": "اي مما يلي مسؤول عن ترجمة اي domain name الي IP و العكس",
        "options": ["DNS", "NAT", "MTU"],
        "correct_answer": "DNS",
        "day": "Day 03 - Network fundamentals",
    },
    {
        "eng_question": "Which of the following is harder for hackers to break the conntection and steal the information",
        "arabic_question": "اي مما يلي من الصعب علي ال hackers قطع الاتصال و سرقة المعلومات منه؟",
        "options": ["HTTP", "HTTPS"],
        "correct_answer": "HTTPS",
        "day": "Day 03 - Network fundamentals",
    },
    {
        "eng_question": "Broad Hop is responsible for checking customer profile from out database ?",
        "arabic_question": "ال Broad Hop هي المسؤول عن التحقق من بيانات العميل في قواعد البيانات الخاصة بنا؟",
        "options": ["True", "False"],
        "correct_answer": "True",
        "day": "Day 03 - Network fundamentals",
    },
    {
        "eng_question": "Which if the below devices is responsible for assigning WAN IPS to CPEs?",
        "arabic_question": "مين من الاجهزة التحت دي مسؤول عن تعيين ال WAN IPS لاجهزة الروتر؟",
        "options": ["DSLAM", "BRAS", "RADIUS"],
        "correct_answer": "BRAS",
        "day": "Day 03 - Network fundamentals",
    },
    {
        "eng_question": "The Ethernet calbe ends with RJ",
        "arabic_question": "كبل ال Ethernet ال بينتهي ب RJ",
        "options": ["45", "11", "40"],
        "correct_answer": "45",
        "day": "Day 03 - Network fundamentals",
    },
    {
        "eng_question": "RADIUS is responsible to make sure that customer using his US & PW which are on our system & related to his line?",
        "arabic_question": "ال RADIUS هو المسؤول عن التأكد ان العميل بيستخدم ال US و ال PW الموجودة علي نظامنا والخاصة ب الخط بتاعو؟",
        "options": ["True", "False"],
        "correct_answer": "True",
        "day": "Day 03 - Network fundamentals",
    },
    {
        "eng_question": "DHCP is assigning automatic LAN IP's to the private devices, But NAT is responsible for translating the Private IP into Public IP",
        "arabic_question": "ال DHCP هو المسؤول عن تعيين LAN IP'S تلقائيا للاجهزة الخاصة, بينما ال NAT هي المسؤوله عن ترجمة و تحويل ال Private IP الي Public IP?",
        "options": ["True", "False"],
        "correct_answer": "True",
        "day": "Day 03 - Network fundamentals",
    },
    {
        "eng_question": "Device is using to split data and voice into 2 channgles",
        "arabic_question": "الجهاز المسؤول عن تقسيم ال data و ال voice الي قناتان مختلفتان؟",
        "options": ["Filter", "Spliter", "Rosetta"],
        "correct_answer": "Spliter",
        "day": "Day 03 - Network fundamentals",
    },
    {
        "eng_question": "ٍSurvey SLA is ..?",
        "arabic_question": "مدة المعاينة",
        "options": ["3 WD", "24H", "24 WH"],
        "correct_answer": "24H",
        "day": "Day 04 - New line Registration",
    },
    {
        "eng_question": "ٍwe can follow up on check availability request through BSS from ..",
        "arabic_question": "احنا ممكن نتابع طلب ال check availability من ال BSS ?",
        "options": [
            "Sitemap >> Integrated Operations >> check cpe by serial",
            "Sitemap >> Integrated Operations >> check availability fixed",
            "Sitemap >> Integrated Operations >>  Search availability PSTN",
        ],
        "correct_answer": "Sitemap >> Integrated Operations >>  Search availability PSTN",
        "day": "Day 04 - New line Registration",
    },
    {
        "eng_question": "In Case CCA found Automatic TT (Automatic TT FV >> Customer Subscription >> OSS TDM Registration) CCA Action Will be ?",
        "arabic_question": "لو لقيت ال Automatic TT دي (Automatic TT FV >> Customer Subscription >> OSS TDM Registration) هتعمل ايه ؟",
        "options": [
            "Make new order",
            "Inform customer that someone will communicate with him within SLA 24H and in case of delay will renew SLA",
            "direct CST to exchange",
        ],
        "correct_answer": "Inform customer that someone will communicate with him within SLA 24H and in case of delay will renew SLA",
        "day": "Day 04 - New line Registration",
    },
    {
        "eng_question": "WE Ardy 20 Quarter price includind fees is",
        "arabic_question": "باقة وي 20 الربع سنوي سعرها كام؟",
        "options": ["75 LE", "65 LE", "68.4 LE"],
        "correct_answer": "68.4 LE",
        "day": "Day 04 - New line Registration",
    },
    {
        "eng_question": "MSAN installation cycle SLA within 48H",
        "arabic_question": "مدة تركيب في ال MSAN 48H ?",
        "options": ["True", "False"],
        "correct_answer": "True",
        "day": "Day 04 - New line Registration",
    },
    {
        "eng_question": "CST want to renew his package (WE Ardy 35 Quarter), CCA will inform him to pay ... LE at least",
        "arabic_question": "هتقول للعميل يشحن بكام لو قلك عاوز يجدد باقة وي ارضي 35 ربع سنوي ؟",
        "options": ["215", "186", "122"],
        "correct_answer": "122",
        "day": "Day 04 - New line Registration",
    },
    {
        "eng_question": "Requested data from customer for check availability",
        "arabic_question": "المعلومات المطلوبة من العميل عشان نعملو Check availability ?",
        "options": [
            "Full name",
            "mobile + Full address",
            "Full name + Mobile + full address + ID number",
        ],
        "correct_answer": "Full name + Mobile + full address + ID number",
        "day": "Day 04 - New line Registration",
    },
    {
        "eng_question": "Modify reason ( Customer Request ) will be done for free for..",
        "arabic_question": "كم عدد المرات المجانية للعميل لتغيير البيانات ؟",
        "options": ["all time", "two times", "one time"],
        "correct_answer": "two times",
        "day": "Day 04 - New line Registration",
    },
    {
        "eng_question": "CCA must choose one of those choices when he make check availability request",
        "arabic_question": "ممثل خدمة العملة لازم يخطار ايه و هو بيعمل check availability request",
        "options": [
            "MSAN FTTH Exchange",
            "FTTH Compound",
            "FTTH Compound \\ Others\\MSAN FTTH Exchange",
        ],
        "correct_answer": "FTTH Compound \\ Others\\MSAN FTTH Exchange",
        "day": "Day 04 - New line Registration",
    },
    {
        "eng_question": "in check availability request ,, CCA can make Request by",
        "arabic_question": "في عملية ال check availability request, ممثل خدمة العملاء بيعمل الطلب ب ايه ؟",
        "options": ["National ID", "Mobil no", "Full name"],
        "correct_answer": "National ID",
        "day": "Day 04 - New line Registration",
    },
    {
        "eng_question": "CST can request to suspend his land line temporary",
        "arabic_question": "العميل ممكن يعمل ايقاف مؤقت للخط بتاعو ؟",
        "options": ["True", "False"],
        "correct_answer": "True",
        "day": "Day 05 - Fixed Voice Migration",
    },
    {
        "eng_question": "CST can request to make his land line reciving only and do not pay his subscribtion fees",
        "arabic_question": "العميل ممكن يقدم طلب تحويل الخط لاستقبال فقط بدون رسوم (مجاني) ؟",
        "options": ["True", "False"],
        "correct_answer": "False",
        "day": "Day 05 - Fixed Voice Migration",
    },
    {
        "eng_question": "Waiting service is free with WE Ardy 20",
        "arabic_question": "خدممة الانتظار مجانية مع باقة وي ارضي 20",
        "options": ["True", "False"],
        "correct_answer": "False",
        "day": "Day 05 - Fixed Voice Migration",
    },
    {
        "eng_question": "we can move land line to another government",
        "arabic_question": "مممكن نحول الخط لمحافظة تانية ؟",
        "options": ["True", "False"],
        "correct_answer": "True",
        "day": "Day 05 - Fixed Voice Migration",
    },
    {
        "eng_question": "CST can change his line category Through 111",
        "arabic_question": "العميل ممكن يحول نوع الخط من خلال 111",
        "options": ["True", "False"],
        "correct_answer": "False",
        "day": "Day 05 - Fixed Voice Migration",
    },
    {
        "eng_question": "CST Can request change offering through 111",
        "arabic_question": "العميل ممكن يغيير الباقة من خلال 111",
        "options": ["True", "False"],
        "correct_answer": "True",
        "day": "Day 05 - Fixed Voice Migration",
    },
    {
        "eng_question": "Before renewal date there is SMS sending to CST to remind him to pay his bill",
        "arabic_question": "في رسالة بتتبعت للعميل عشان تفكرو بلتجديد ؟",
        "options": ["True", "False"],
        "correct_answer": "True",
        "day": "Day 05 - Fixed Voice Migration",
    },
    {
        "eng_question": "calling WE Mobil and Local calls are active without CST Request",
        "arabic_question": "خدمة ال WE Mobile + local Calls بيكونو شغالين من غير طلب العميل ؟",
        "options": ["True", "False"],
        "correct_answer": "True",
        "day": "Day 05 - Fixed Voice Migration",
    },
    {
        "eng_question": "temporary suspension service Fees without VAT",
        "arabic_question": "سعر الايقاف المؤقت بدون الضريبة ؟",
        "options": ["20 LE", "30 LE", "50 LE"],
        "correct_answer": "20",
        "day": "Day 05 - Fixed Voice Migration",
    },
    {
        "eng_question": "Recharge through Electronic machines is update within 48H",
        "arabic_question": "الشحن من خلال المكينات الاليه بيتحدث خلال 48H",
        "options": ["True", "False"],
        "correct_answer": "False",
        "day": "Day 05 - Fixed Voice Migration",
    },
    {
        "eng_question": "SLA for new Account is",
        "arabic_question": "ال SLA الخاصة بالاشتراك الجديد هي",
        "options": ["72H", "48 WH", "3 Days"],
        "correct_answer": "48 WH",
        "day": "Day 06 - Tools and New subscription",
    },
    {
        "eng_question": "We can determined port configured speed from which tool ",
        "arabic_question": "Port Configured speed نقدر نشوف منين",
        "options": ["Matrix", "OSS", "OM"],
        "correct_answer": "Matrix",
        "day": "Day 06 - Tools and New subscription",
    },
    {
        "eng_question": "All Branches have same Working Hours and Days off ",
        "arabic_question": "الفروع ليها نفس مواعيد العمل والاجازات",
        "options": ["True", "False"],
        "correct_answer": "False",
        "day": "Day 06 - Tools and New subscription",
    },
    {
        "eng_question": "We can check customer if Blocked or not from which tool",
        "arabic_question": "من خلال Blocked or not نقدر نشوف خط العميل",
        "options": ["Matrix", "OSS", "OM"],
        "correct_answer": "Matrix",
        "day": "Day 06 - Tools and New subscription",
    },
    {
        "eng_question": "Our customers can not submit any tkt from WE APP",
        "arabic_question": "عملاء شركة WE لا يمكنهم تقديم أي شكوي من خلال WE APP",
        "options": ["True", "False"],
        "correct_answer": "False",
        "day": "Day 06 - Tools and New subscription",
    },
    {
        "eng_question": "Which Tool we Can Know any another( Q ) Working Hours",
        "arabic_question": "نقدر نعرف مواعيد الاقسام الاخرى من خلال",
        "options": ["CST 360", "IVR", "Branch"],
        "correct_answer": "IVR",
        "day": "Day 06 - Tools and New subscription",
    },
    {
        "eng_question": "New subscription can apply through",
        "arabic_question": "الاشتراكات الجديدة تتم من خلال",
        "options": ["Call Center Only", "Branch only", "Both of them"],
        "correct_answer": "Branch only",
        "day": "Day 06 - Tools and New subscription",
    },
    {
        "eng_question": "Some Of Corporate Individual Postpaid Customers bill cycle on ?",
        "arabic_question": "نظام دورة الفاتورة الخاصة ببعض عملاء ال Corporate Individual Postpaid",
        "options": [
            "Day 16 from each month",
            "Day 1 from each month",
            "Day 22 from each month",
        ],
        "correct_answer": "Day 22 from each month",
        "day": "Day 06 - Tools and New subscription",
    },
    {
        "eng_question": "Which service customer can use static IP",
        "arabic_question": "ما هي الخدمة التي يستطيع العميل من خلالها استخدام ال static IP",
        "options": ["option pack", "Family Filter", "IPTV"],
        "correct_answer": "option pack",
        "day": "Day 06 - Tools and New subscription",
    },
    {
        "eng_question": "One invoice postpaid corporate Customer want to make early renewal CCA action will be …?",
        "arabic_question": "عميل One invoice postpaid corporate طلب عمل تجديد مبكر للخدمة, ال CCA action will be",
        "options": [
            "Make verification then make early renewal to CST from BSS عمل تأكيد على البيانات ثم عمل تجديد مبكر للخدمة من خلال ال BSS",
            "Direct Customer to his SPOC توجيه العميل لمتابعة الطلب مع ال SPOC",
            "Inform CST that he can't make early renewal + Create SR ابلاغ العميل بعدم القدرة على عمل طلب تجديد مبكر للخدمة + عمل SR",
        ],
        "correct_answer": "Inform CST that he can't make early renewal + Create SR ابلاغ العميل بعدم القدرة على عمل طلب تجديد مبكر للخدمة + عمل SR",
        "day": "Day 06 - Tools and New subscription",
    },
    {
        "eng_question": "CST call from same landline number and ask for early renewal CCA will ask CST about … To Verification ?",
        "arabic_question": "لو العميل بيتكلم من نفس رقم الارضي و بيطلب يعمل تجديد مبكر هتعمل verification ازاي ؟",
        "options": [
            "Full Name +  Last 3 digit of mobile number",
            "No Need Any Verification Rules",
            "last 7 digit of nation ID + Mobile Number",
        ],
        "correct_answer": "No Need Any Verification Rules",
        "day": "Day 07 - Tools and Follow Up",
    },
    {
        "eng_question": "Any TT Must be Problem / Non-Om Problem when CCA choose from Additional Information ?",
        "arabic_question": "اي TT لازم تكون Problem / Non-Om Problem عند الاختيار من Additional Information",
        "options": ["True", "False"],
        "correct_answer": "False",
        "day": "Day 07 - Tools and Follow Up",
    },
    {
        "eng_question": "Line Problem SLA Is ….?",
        "arabic_question": "ال SLA الخاصة بمشكلة ال Line Problem هي...؟",
        "options": ["15 WD", "7 WD", "2 WD"],
        "correct_answer": "15 WD",
        "day": "Day 07 - Tools and Follow Up",
    },
    {
        "eng_question": "TE Problem No Technical Data means …?",
        "arabic_question": "  “TE Problem No Technical Data” تعني",
        "options": [
            "No Data",
            "No technical Data for Line In TE",
            "No Financial  Data for Line In TE",
        ],
        "correct_answer": "No technical Data for Line In TE",
        "day": "Day 07 - Tools and Follow Up",
    },
    {
        "eng_question": "In Case Of Delay In Port Splitting Activity CCA Action Will Be…?",
        "arabic_question": "في حالة حدوث تأخير في مرحلة ال Port Splitting, يجب على ال CCA أن .....؟",
        "options": [
            "Create TT And Inform CST SLA 48 WH",
            "Create SR FBB Non Tech follow up--InstallationOrder--Splitting After SLA / Inform CST 48 H",
            "Automatic TT Will Be Created",
        ],
        "correct_answer": "Create TT And Inform CST SLA 48 WH",
        "day": "Day 07 - Tools and Follow Up",
    },
    {
        "eng_question": "Any SR will be Inquiry/offers except complain SR?",
        "arabic_question": "كل ال SR بتكون inquiry/offers معادا ال complains SR?",
        "options": ["True", "False"],
        "correct_answer": "True",
        "day": "Day 07 - Tools and Follow Up",
    },
    {
        "eng_question": "In Case WO Request and there is problem happened sub activity will be….?",
        "arabic_question": "في حالة حدوث مشكلة خلال مرحلة ال WO Request ال sub activity will be...؟",
        "options": ["Line Problem", "WO Problem", "TE Problem"],
        "correct_answer": "WO Problem",
        "day": "Day 07 - Tools and Follow Up",
    },
    {
        "eng_question": "Check Free Port SLA …?",
        "arabic_question": "ال SLA الخاصة بمشكلة Check free port هي....؟",
        "options": ["No Estimated Time", "1 WD", "48 H"],
        "correct_answer": "No Estimated Time",
        "day": "Day 07 - Tools and Follow Up",
    },
    {
        "eng_question": "CCA Must Make TT ….. In Case No Technical Data Found On Matrix Tool After Call Back To CRM ?",
        "arabic_question": "من الضروري على ال CCA عمل TT......... في حالة عدم وجود أي بيانات فنية للعميل على ال Matrix tool بعد وصول التركيبات الي مرحلة ال Call Back To CRM..؟",
        "options": ["Create Matrix TT", "Duplicated Matrix TT", "Remove Matrix TT"],
        "correct_answer": "Create Matrix TT",
        "day": "Day 07 - Tools and Follow Up",
    },
    {
        "eng_question": "To Review All created tickets CCA can choose …?",
        "arabic_question": "لمعرفة كل الشكاوي التي تم انشاءها من قبل يجب اختيار ...؟",
        "options": [
            "Modify Customer Information",
            "Creat service Request",
            "Trouble Ticket",
        ],
        "correct_answer": "Trouble Ticket",
        "day": "Day 07 - Tools and Follow Up",
    },
    {
        "eng_question": "CST has noise problem and has physical instability issue CCA will handle …?",
        "arabic_question": "موظف خدمة العملاء سيتابع noise problem and has physical instability issue عميل يواجه",
        "options": [
            "voice down",
            "Physical instability",
            "noise issue",
        ],
        "correct_answer": "Physical instability",
        "day": "Day 08 - Voice Cases",
    },
    {
        "eng_question": "in voice verification .. After calling CST's on landline number CCA found Record Massage الرقم مرفوع مؤقت من الخدمة  CCA action will be…?",
        "arabic_question": "بعد الاتصال بالخط الارضي للعميل موظف خدمة العملاء وجد رسالة ( الرقم مرفوع مؤقت من الخدمة) ما هو الاجراء المناسب  voice verification اثناء",
        "options": [
            "Consider Voice Down + Create TT Create TT + اعتبار الحرارة فاصلة",
            "Consider Voice Up + Create SR Create SR + اعتبار الحرارة شغالة",
            "Ask CST to pay landline bills اطلب من العميل دفع الفواتير الارضي",
        ],
        "correct_answer": "Consider Voice Down + Create TT Create TT + اعتبار الحرارة فاصلة",
        "day": "Day 08 - Voice Cases",
    },
    {
        "eng_question": "CST Follow voice down ticket after 25 hour from escalating it and ticket still on IU CCA action will be …?",
        "arabic_question": "ا هو الاجراء المناسب  IU  بعد 25 ساعة من تصعيد الشكوى ومازالت موجودة فى قسم voice down ticket عميل بيتابع على",
        "options": [
            "Re-escalate Ticket + create SR ​​FBB Tech Problem---​Voice Down​---​Re-Escalation create SR ​​FBB Tech Problem---​Voice Down​---​Re-Escalation + Ticket اعادة تصعيد"
            "Inform CST Within  SLA +create SR ​​FBB Tech Problem---​Voice Down​---Follow Up create SR ​​FBB Tech Problem---​Voice Down​---Follow Up + اخبار العميل بانه فى خلال المدة",
            "Inform CST Passed SLA + Create IR +create SR ​​FBB Tech Problem---​Voice Down​---Follow Up after SLA Create IR +create SR ​​FBB Tech Problem---​Voice Down​---Follow Up after SLA + اخبار العميل بتجاوز المدة",
        ],
        "correct_answer": "Inform CST Passed SLA + Create IR +create SR ​​FBB Tech Problem---​Voice Down​---Follow Up after SLA Create IR +create SR ​​FBB Tech Problem---​Voice Down​---Follow Up after SLA + اخبار العميل بتجاوز المدة",
        "day": "Day 08 - Voice Cases",
    },
    {
        "eng_question": "CST has problem in Call waiting service CCA action will be ..?",
        "arabic_question": "ماهو الاجراء المناسب Call waiting عميل يواجه مشكلة فى خدمة",
        "options": [
            "Transfer CST to fixed line VDN تحويل العميل لقسم الخط الارضي"
            "Escalate Voice Down Voice Down تصعيد",
            "Inform CST to pay all landline bills اخبار العميل بدفع فواتير الخط الارضي",
        ],
        "correct_answer": "Transfer CST to fixed line VDN تحويل العميل لقسم الخط الارضي",
        "day": "Day 08 - Voice Cases",
    },
    {
        "eng_question": "Customer problem voice not working or out of service after pay bill after cut off and informed that issue started before cutoff date , CCA Right Action",
        "arabic_question": "ما هو الاجراء المناسب cutoff date وابلغنا ان المشكلة بدأت قبل cut off عميل يواجه انقطاع الحرارة او خارج الخدمة بعد دفع الفاتورة بعد",
        "options": [
            "Phone set available step السؤال عن عدة تليفون متاحة",
            "Transfer CST to fixed line Q تحويل العميل الى الخط الارضي",
            "Create UCRM ( RCR Complaint ) UCRM عمل شكوى على",
        ],
        "correct_answer": "Phone set available step السؤال عن عدة تليفون متاحة",
        "day": "Day 08 - Voice Cases",
    },
    {
        "eng_question": "CCA found that CST's landline number has work order رفع نهائي متأخرات أقساط  In Customer Profile Tool ..... CCA action will be…?",
        "arabic_question": "ماهو الاجراء المناسب Customer Profile Tool  موظف خدمة العملاء وجد امر الشغل الخاص بالخط الارضي للعميل ( رفع نهائي متأخرات أقساط)  فى",
        "options": [
            "Inform CST to pay all due installments اخبار العميل دفع الاقساط  المستحقة",
            "Inform CST to pay all landline bills اخبار العميل دفع فواتير الخط الارضي",
            "Follow change phone number process change phone number متابعة اجراءات",
        ],
        "correct_answer": "Inform CST to pay all due installments اخبار العميل دفع الاقساط  المستحقة",
        "day": "Day 08 - Voice Cases",
    },
    {
        "eng_question": "Voice overlapping can happened between?",
        "arabic_question": "يمكن ان تحدث بين Voice overlapping",
        "options": [
            "2 numbers with same government رقمين فى نفس المحافظة",
            "2 numbers in the different  exchange رقمين فى سنترال مختلف",
            "2 numbers in the same exchange رقمين فى نفس السنترال",
        ],
        "correct_answer": "2 numbers in the same exchange رقمين فى نفس السنترال",
        "day": "Day 08 - Voice Cases",
    },
    {
        "eng_question": "CCA must check voice verification before escalating?",
        "arabic_question": ":قبل تصعيد voice verification يجب على موظف خدمة العملاء التأكد من",
        "options": [
            "All physical cases",
            "Data Down only",
            "logical cases",
        ],
        "correct_answer": "All physical cases",
        "day": "Day 08 - Voice Cases",
    },
    {
        "eng_question": "Voice Cases override any physical case?",
        "arabic_question": "؟physical تتجاوز اى مشكلة Voice  مشاكل",
        "options": [
            "True",
            "Flase",
        ],
        "correct_answer": "True",
        "day": "Day 08 - Voice Cases",
    },
    {
        "eng_question": "Voice Down TT SLA is?",
        "arabic_question": "؟ Voice Down المدة المحددة لحل مشكلة",
        "options": [
            "2 Days",
            "1 Days",
            "3 Days",
        ],
        "correct_answer": "1 Days",
        "day": "Day 08 - Voice Cases",
    },
    {
        "eng_question": "If CST has landline bill with 75 LE CCA action will be?",
        "arabic_question": "لو العميل عليه فاتوره ب 75 جنيه, هتعمل ايه يا باشا ؟",
        "options": [
            "Check voice status",
            "Stop troublshoting and inform CST to pay all due bills",
            "Check grace period",
        ],
        "correct_answer": "Check grace period",
        "day": "Day 08 - Voice Cases",
    },
    {
        "eng_question": "If CST is calling from the same landline number that's means?",
        "arabic_question": "لو العميل بيكلمك يا معلم من نفس رقم الارضي, فماذا يعني هذا",
        "options": [
            "CST has landline bill",
            "Voice maybe down",
            "Voice is working fine",
        ],
        "correct_answer": "Voice is working fine",
        "day": "Day 08 - Voice Cases",
    },
    {
        "eng_question": "CST is calling from different landline number and inform us that voice is working CCA action will be ?",
        "arabic_question": "العميل كلمك من رقم ارضي مختلف و قلك ال Voice زي الفل يا صحبي, هتعمل ايه ؟",
        "options": [
            "Consider voice up",
            "Call CST landline number",
            "Should confirm with CST first if tested voice via phone set before call",
        ],
        "correct_answer": "Should confirm with CST first if tested voice via phone set before call",
        "day": "Day 08 - Voice Cases",
    },
    {
        "eng_question": "CST is calling from different landline number and inform us that voice is working but havn't phone set available, CCA action will be?",
        "arabic_question": "العميل كلمك من خط ارضي مختلف و قلك ال Voice شغال تمام بس مفيش عدة ارضي والله, هتعنل ايه ؟",
        "options": [
            "Ask CST to test voice by phone set",
            "Consider Voice Up + Create SR",
            "Put CST on hold and call CST landline number",
        ],
        "correct_answer": "Put CST on hold and call CST landline number",
        "day": "Day 08 - Voice Cases",
    },
    {
        "eng_question": "If we call CST on his ADSL number to check voice status, we find another person respond, your action",
        "arabic_question": "بتكلم العميل عشان تشوف حاله ال Voice رد عليك حد تاني, هتعمل ايه؟ (خلبالك دا كمين)",
        "options": [
            "Consider Voice Up + Create SR",
            "TS Voice overlapping",
            "Confirm landline number",
        ],
        "correct_answer": "Confirm landline number",
        "day": "Day 08 - Voice Cases",
    },
    {
        "eng_question": "CST has data down after checking voice CCA found voice is also down, CCA will escalate?",
        "arabic_question": "العميل ال data عنده down و بعد فحص ال Voice طلع هو كمان down, (افتكر مين ديما بتبقي مع مين) هتصعد ايه؟",
        "options": [
            "Data down",
            "Voice down",
            "Data and Voice Down",
        ],
        "correct_answer": "Data and Voice Down",
        "day": "Day 08 - Voice Cases",
    },
    {
        "eng_question": "Customer Problem Voice not working or out of service after paid his bill after cut off date and CST confirmed that issue started from cut off date?",
        "arabic_question": "العميل عنده voice مش شغال او out of service بعد دفع الفواتير و بعد تاريخ ال Cut Off بعد مع ال agent أكد ان المشكله من تاريخ ال Cut off",
        "options": [
            "Transfer CST to fixed line Q",
            "Phone set available step",
            "Create UCRM (RCR Complain)",
        ],
        "correct_answer": "Create UCRM (RCR Complain)",
        "day": "Day 08 - Voice Cases",
    },
    {
        "eng_question": "Voice not working or out of service and voice problem wasn't due to unpaid landline bills and still exist after paying the bill CCA action will be?",
        "arabic_question": "ال Voice down او out of service و المشكلة مش في الفواتير و المشكله لسا موجوده حتي بعد دفع الفواتير؟",
        "options": [
            "Create UCRM (RCR Complaint)",
            "Transfer CST to fixed line Q",
            "Phone set available step",
        ],
        "correct_answer": "Phone set available step",
        "day": "Day 08 - Voice Cases",
    },
    {
        "eng_question": "The first step of voice verification if CST is not migrated to BSS is",
        "arabic_question": "اول خطوه في ال voice verfication لو العميل مش علي ال BSS",
        "options": [
            "Check CST calling from same ADSL number",
            "Check landline bills",
            "Check voice from main",
        ],
        "correct_answer": "Check landline bills",
        "day": "Day 08 - Voice Cases",
    },
    {
        "eng_question": "Voice verification steps, that's meaning you have to check landline bills and .. ?",
        "arabic_question": "ال voice verification بتشوف فيها الفواتير و ايه .؟",
        "options": [
            "Check noise or weird voice",
            "Check grace period",
            "Check voice status",
        ],
        "correct_answer": "Check voice status",
        "day": "Day 08 - Voice Cases",
    },
]
