questions = [
    {
        "eng_question": "We have two types of connection (Main Wire and wall outlet)",
        "arabic_question": "وجد لدينا نوعين من التوصيل (Main Wire and wall outlet)",
        "options": ["True", "False"],
        "correct_answer": "True",
        "day": "Day 03 - Network fundamentals",
    },
    {
        "eng_question": "In CPE configuration 'VDSL' Parameters XDSL Transfer Mode Should be ?",
        "arabic_question": "ال 'VDSL' Parameters CDSL Transfer Mode في اعدادات الروتر يجب ان تكون ",
        "options": ["PPPOE", "PPP", "PTM"],
        "correct_answer": "PTM",
        "day": "Day 03 - Network fundamentals",
    },
    {
        "eng_question": "Which of the below is the responsible for translating any domain name into IP and Vice Versa",
        "arabic_question": "اي مما يلي مسؤول عن ترجمة اي domain name الي IP و العكس",
        "options": ["DNS", "NAT", "MTU"],
        "correct_answer": "DNS",
        "day": "Day 03 - Network fundamentals",
    },
    {
        "eng_question": "Which of the following is harder for hackers to break the conntection and steal the information",
        "arabic_question": "اي مما يلي من الصعب علي ال hackers قطع الاتصال و سرقة المعلومات منه؟",
        "options": ["HTTP", "HTTPS"],
        "correct_answer": "HTTPS",
        "day": "Day 03 - Network fundamentals",
    },
    {
        "eng_question": "Broad Hop is responsible for checking customer profile from out database ?",
        "arabic_question": "ال Broad Hop هي المسؤول عن التحقق من بيانات العميل في قواعد البيانات الخاصة بنا؟",
        "options": ["True", "False"],
        "correct_answer": "True",
        "day": "Day 03 - Network fundamentals",
    },
    {
        "eng_question": "Which if the below devices is responsible for assigning WAN IPS to CPEs?",
        "arabic_question": "مين من الاجهزة التحت دي مسؤول عن تعيين ال WAN IPS لاجهزة الروتر؟",
        "options": ["DSLAM", "BRAS", "RADIUS"],
        "correct_answer": "BRAS",
        "day": "Day 03 - Network fundamentals",
    },
    {
        "eng_question": "The Ethernet calbe ends with RJ",
        "arabic_question": "كبل ال Ethernet ال بينتهي ب RJ",
        "options": ["45", "11", "40"],
        "correct_answer": "45",
        "day": "Day 03 - Network fundamentals",
    },
    {
        "eng_question": "RADIUS is responsible to make sure that customer using his US & PW which are on our system & related to his line?",
        "arabic_question": "ال RADIUS هو المسؤول عن التأكد ان العميل بيستخدم ال US و ال PW الموجودة علي نظامنا والخاصة ب الخط بتاعو؟",
        "options": ["True", "False"],
        "correct_answer": "True",
        "day": "Day 03 - Network fundamentals",
    },
    {
        "eng_question": "DHCP is assigning automatic LAN IP's to the private devices, But NAT is responsible for translating the Private IP into Public IP",
        "arabic_question": "ال DHCP هو المسؤول عن تعيين LAN IP'S تلقائيا للاجهزة الخاصة, بينما ال NAT هي المسؤوله عن ترجمة و تحويل ال Private IP الي Public IP?",
        "options": ["True", "False"],
        "correct_answer": "True",
        "day": "Day 03 - Network fundamentals",
    },
    {
        "eng_question": "Device is using to split data and voice into 2 channgles",
        "arabic_question": "الجهاز المسؤول عن تقسيم ال data و ال voice الي قناتان مختلفتان؟",
        "options": ["Filter", "Spliter", "Rosetta"],
        "correct_answer": "Spliter",
        "day": "Day 03 - Network fundamentals",
    },
    {
        "eng_question": "ٍSurvey SLA is ..?",
        "arabic_question": "مدة المعاينة",
        "options": ["3 WD", "24H", "24 WH"],
        "correct_answer": "24H",
        "day": "Day 04 - New line Registration",
    },
    {
        "eng_question": "ٍwe can follow up on check availability request through BSS from ..",
        "arabic_question": "احنا ممكن نتابع طلب ال check availability من ال BSS ?",
        "options": [
            "Sitemap >> Integrated Operations >> check cpe by serial",
            "Sitemap >> Integrated Operations >> check availability fixed",
            "Sitemap >> Integrated Operations >>  Search availability PSTN",
        ],
        "correct_answer": "Sitemap >> Integrated Operations >>  Search availability PSTN",
        "day": "Day 04 - New line Registration",
    },
    {
        "eng_question": "In Case CCA found Automatic TT (Automatic TT FV >> Customer Subscription >> OSS TDM Registration) CCA Action Will be ?",
        "arabic_question": "لو لقيت ال Automatic TT دي (Automatic TT FV >> Customer Subscription >> OSS TDM Registration) هتعمل ايه ؟",
        "options": [
            "Make new order",
            "Inform customer that someone will communicate with him within SLA 24H and in case of delay will renew SLA",
            "direct CST to exchange",
        ],
        "correct_answer": "Inform customer that someone will communicate with him within SLA 24H and in case of delay will renew SLA",
        "day": "Day 04 - New line Registration",
    },
    {
        "eng_question": "WE Ardy 20 Quarter price includind fees is",
        "arabic_question": "باقة وي 20 الربع سنوي سعرها كام؟",
        "options": ["75 LE", "65 LE", "68.4 LE"],
        "correct_answer": "68.4 LE",
        "day": "Day 04 - New line Registration",
    },
    {
        "eng_question": "MSAN installation cycle SLA within 48H",
        "arabic_question": "مدة تركيب في ال MSAN 48H ?",
        "options": ["True", "False"],
        "correct_answer": "True",
        "day": "Day 04 - New line Registration",
    },
    {
        "eng_question": "CST want to renew his package (WE Ardy 35 Quarter), CCA will inform him to pay ... LE at least",
        "arabic_question": "هتقول للعميل يشحن بكام لو قلك عاوز يجدد باقة وي ارضي 35 ربع سنوي ؟",
        "options": ["215", "186", "122"],
        "correct_answer": "122",
        "day": "Day 04 - New line Registration",
    },
    {
        "eng_question": "Requested data from customer for check availability",
        "arabic_question": "المعلومات المطلوبة من العميل عشان نعملو Check availability ?",
        "options": [
            "Full name",
            "mobile + Full address",
            "Full name + Mobile + full address + ID number",
        ],
        "correct_answer": "Full name + Mobile + full address + ID number",
        "day": "Day 04 - New line Registration",
    },
    {
        "eng_question": "Modify reason ( Customer Request ) will be done for free for..",
        "arabic_question": "كم عدد المرات المجانية للعميل لتغيير البيانات ؟",
        "options": ["all time", "two times", "one time"],
        "correct_answer": "two times",
        "day": "Day 04 - New line Registration",
    },
    {
        "eng_question": "CCA must choose one of those choices when he make check availability request",
        "arabic_question": "ممثل خدمة العملة لازم يخطار ايه و هو بيعمل check availability request",
        "options": [
            "MSAN FTTH Exchange",
            "FTTH Compound",
            "FTTH Compound \\ Others\\MSAN FTTH Exchange",
        ],
        "correct_answer": "FTTH Compound \\ Others\\MSAN FTTH Exchange",
        "day": "Day 04 - New line Registration",
    },
    {
        "eng_question": "in check availability request ,, CCA can make Request by",
        "arabic_question": "في عملية ال check availability request, ممثل خدمة العملاء بيعمل الطلب ب ايه ؟",
        "options": ["National ID", "Mobil no", "Full name"],
        "correct_answer": "National ID",
        "day": "Day 04 - New line Registration",
    },
    {
        "eng_question": "CST can request to suspend his land line temporary",
        "arabic_question": "العميل ممكن يعمل ايقاف مؤقت للخط بتاعو ؟",
        "options": ["True", "False"],
        "correct_answer": "True",
        "day": "Day 05 - Fixed Voice Migration",
    },
    {
        "eng_question": "CST can request to make his land line reciving only and do not pay his subscribtion fees",
        "arabic_question": "العميل ممكن يقدم طلب تحويل الخط لاستقبال فقط بدون رسوم (مجاني) ؟",
        "options": ["True", "False"],
        "correct_answer": "False",
        "day": "Day 05 - Fixed Voice Migration",
    },
    {
        "eng_question": "Waiting service is free with WE Ardy 20",
        "arabic_question": "خدممة الانتظار مجانية مع باقة وي ارضي 20",
        "options": ["True", "False"],
        "correct_answer": "False",
        "day": "Day 05 - Fixed Voice Migration",
    },
    {
        "eng_question": "we can move land line to another government",
        "arabic_question": "مممكن نحول الخط لمحافظة تانية ؟",
        "options": ["True", "False"],
        "correct_answer": "True",
        "day": "Day 05 - Fixed Voice Migration",
    },
    {
        "eng_question": "CST can change his line category Through 111",
        "arabic_question": "العميل ممكن يحول نوع الخط من خلال 111",
        "options": ["True", "False"],
        "correct_answer": "False",
        "day": "Day 05 - Fixed Voice Migration",
    },
    {
        "eng_question": "CST Can request change offering through 111",
        "arabic_question": "العميل ممكن يغيير الباقة من خلال 111",
        "options": ["True", "False"],
        "correct_answer": "True",
        "day": "Day 05 - Fixed Voice Migration",
    },
    {
        "eng_question": "Before renewal date there is SMS sending to CST to remind him to pay his bill",
        "arabic_question": "في رسالة بتتبعت للعميل عشان تفكرو بلتجديد ؟",
        "options": ["True", "False"],
        "correct_answer": "True",
        "day": "Day 05 - Fixed Voice Migration",
    },
    {
        "eng_question": "calling WE Mobil and Local calls are active without CST Request",
        "arabic_question": "خدمة ال WE Mobile + local Calls بيكونو شغالين من غير طلب العميل ؟",
        "options": ["True", "False"],
        "correct_answer": "True",
        "day": "Day 05 - Fixed Voice Migration",
    },
    {
        "eng_question": "temporary suspension service Fees without VAT",
        "arabic_question": "سعر الايقاف المؤقت بدون الضريبة ؟",
        "options": ["20 LE", "30 LE", "50 LE"],
        "correct_answer": "20",
        "day": "Day 05 - Fixed Voice Migration",
    },
    {
        "eng_question": "Recharge through Electronic machines is update within 48H",
        "arabic_question": "الشحن من خلال المكينات الاليه بيتحدث خلال 48H",
        "options": ["True", "False"],
        "correct_answer": "False",
        "day": "Day 05 - Fixed Voice Migration",
    },
    {
        "eng_question": "SLA for new Account is",
        "arabic_question": "ال SLA الخاصة بالاشتراك الجديد هي",
        "options": ["72H", "48 WH", "3 Days"],
        "correct_answer": "48 WH",
        "day": "Day 06 - Tools and New subscription",
    },
    {
        "eng_question": "We can determined port configured speed from which tool ",
        "arabic_question": "Port Configured speed نقدر نشوف منين",
        "options": ["Matrix", "OSS", "OM"],
        "correct_answer": "Matrix",
        "day": "Day 06 - Tools and New subscription",
    },
    {
        "eng_question": "All Branches have same Working Hours and Days off ",
        "arabic_question": "الفروع ليها نفس مواعيد العمل والاجازات",
        "options": ["True", "False"],
        "correct_answer": "False",
        "day": "Day 06 - Tools and New subscription",
    },
    {
        "eng_question": "We can check customer if Blocked or not from which tool",
        "arabic_question": "من خلال Blocked or not نقدر نشوف خط العميل",
        "options": ["Matrix", "OSS", "OM"],
        "correct_answer": "Matrix",
        "day": "Day 06 - Tools and New subscription",
    },
    {
        "eng_question": "Our customers can not submit any tkt from WE APP",
        "arabic_question": "عملاء شركة WE لا يمكنهم تقديم أي شكوي من خلال WE APP",
        "options": ["True", "False"],
        "correct_answer": "False",
        "day": "Day 06 - Tools and New subscription",
    },
    {
        "eng_question": "Which Tool we Can Know any another( Q ) Working Hours",
        "arabic_question": "نقدر نعرف مواعيد الاقسام الاخرى من خلال",
        "options": ["CST 360", "IVR", "Branch"],
        "correct_answer": "IVR",
        "day": "Day 06 - Tools and New subscription",
    },
    {
        "eng_question": "New subscription can apply through",
        "arabic_question": "الاشتراكات الجديدة تتم من خلال",
        "options": ["Call Center Only", "Branch only", "Both of them"],
        "correct_answer": "Branch only",
        "day": "Day 06 - Tools and New subscription",
    },
    {
        "eng_question": "Some Of Corporate Individual Postpaid Customers bill cycle on ?",
        "arabic_question": "نظام دورة الفاتورة الخاصة ببعض عملاء ال Corporate Individual Postpaid",
        "options": [
            "Day 16 from each month",
            "Day 1 from each month",
            "Day 22 from each month",
        ],
        "correct_answer": "Day 22 from each month",
        "day": "Day 06 - Tools and New subscription",
    },
    {
        "eng_question": "Which service customer can use static IP",
        "arabic_question": "ما هي الخدمة التي يستطيع العميل من خلالها استخدام ال static IP",
        "options": ["option pack", "Family Filter", "IPTV"],
        "correct_answer": "option pack",
        "day": "Day 06 - Tools and New subscription",
    },
    {
        "eng_question": "One invoice postpaid corporate Customer want to make early renewal CCA action will be …?",
        "arabic_question": "عميل One invoice postpaid corporate طلب عمل تجديد مبكر للخدمة, ال CCA action will be",
        "options": [
            "Make verification then make early renewal to CST from BSS عمل تأكيد على البيانات ثم عمل تجديد مبكر للخدمة من خلال ال BSS",
            "Direct Customer to his SPOC توجيه العميل لمتابعة الطلب مع ال SPOC",
            "Inform CST that he can't make early renewal + Create SR ابلاغ العميل بعدم القدرة على عمل طلب تجديد مبكر للخدمة + عمل SR",
        ],
        "correct_answer": "Inform CST that he can't make early renewal + Create SR ابلاغ العميل بعدم القدرة على عمل طلب تجديد مبكر للخدمة + عمل SR",
        "day": "Day 06 - Tools and New subscription",
    },
    {
        "eng_question": "CST call from same landline number and ask for early renewal CCA will ask CST about … To Verification ?",
        "arabic_question": "لو العميل بيتكلم من نفس رقم الارضي و بيطلب يعمل تجديد مبكر هتعمل verification ازاي ؟",
        "options": [
            "Full Name +  Last 3 digit of mobile number",
            "No Need Any Verification Rules",
            "last 7 digit of nation ID + Mobile Number",
        ],
        "correct_answer": "No Need Any Verification Rules",
        "day": "Day 07 - Tools and Follow Up",
    },
    {
        "eng_question": "Any TT Must be Problem / Non-Om Problem when CCA choose from Additional Information ?",
        "arabic_question": "اي TT لازم تكون Problem / Non-Om Problem عند الاختيار من Additional Information",
        "options": ["True", "False"],
        "correct_answer": "False",
        "day": "Day 07 - Tools and Follow Up",
    },
    {
        "eng_question": "Line Problem SLA Is ….?",
        "arabic_question": "ال SLA الخاصة بمشكلة ال Line Problem هي...؟",
        "options": ["15 WD", "7 WD", "2 WD"],
        "correct_answer": "15 WD",
        "day": "Day 07 - Tools and Follow Up",
    },
    {
        "eng_question": "TE Problem No Technical Data means …?",
        "arabic_question": "  “TE Problem No Technical Data” تعني",
        "options": [
            "No Data",
            "No technical Data for Line In TE",
            "No Financial  Data for Line In TE",
        ],
        "correct_answer": "No technical Data for Line In TE",
        "day": "Day 07 - Tools and Follow Up",
    },
    {
        "eng_question": "In Case Of Delay In Port Splitting Activity CCA Action Will Be…?",
        "arabic_question": "في حالة حدوث تأخير في مرحلة ال Port Splitting, يجب على ال CCA أن .....؟",
        "options": [
            "Create TT And Inform CST SLA 48 WH",
            "Create SR FBB Non Tech follow up--InstallationOrder--Splitting After SLA / Inform CST 48 H",
            "Automatic TT Will Be Created",
        ],
        "correct_answer": "Create TT And Inform CST SLA 48 WH",
        "day": "Day 07 - Tools and Follow Up",
    },
    {
        "eng_question": "Any SR will be Inquiry/offers except complain SR?",
        "arabic_question": "كل ال SR بتكون inquiry/offers معادا ال complains SR?",
        "options": ["True", "False"],
        "correct_answer": "True",
        "day": "Day 07 - Tools and Follow Up",
    },
    {
        "eng_question": "In Case WO Request and there is problem happened sub activity will be….?",
        "arabic_question": "في حالة حدوث مشكلة خلال مرحلة ال WO Request ال sub activity will be...؟",
        "options": ["Line Problem", "WO Problem", "TE Problem"],
        "correct_answer": "WO Problem",
        "day": "Day 07 - Tools and Follow Up",
    },
    {
        "eng_question": "Check Free Port SLA …?",
        "arabic_question": "ال SLA الخاصة بمشكلة Check free port هي....؟",
        "options": ["No Estimated Time", "1 WD", "48 H"],
        "correct_answer": "No Estimated Time",
        "day": "Day 07 - Tools and Follow Up",
    },
    {
        "eng_question": "CCA Must Make TT ….. In Case No Technical Data Found On Matrix Tool After Call Back To CRM ?",
        "arabic_question": "من الضروري على ال CCA عمل TT......... في حالة عدم وجود أي بيانات فنية للعميل على ال Matrix tool بعد وصول التركيبات الي مرحلة ال Call Back To CRM..؟",
        "options": ["Create Matrix TT", "Duplicated Matrix TT", "Remove Matrix TT"],
        "correct_answer": "Create Matrix TT",
        "day": "Day 07 - Tools and Follow Up",
    },
    {
        "eng_question": "To Review All created tickets CCA can choose …?",
        "arabic_question": "لمعرفة كل الشكاوي التي تم انشاءها من قبل يجب اختيار ...؟",
        "options": [
            "Modify Customer Information",
            "Creat service Request",
            "Trouble Ticket",
        ],
        "correct_answer": "Trouble Ticket",
        "day": "Day 07 - Tools and Follow Up",
    },
    {
        "eng_question": "CST has noise problem and has physical instability issue CCA will handle …?",
        "arabic_question": "موظف خدمة العملاء سيتابع noise problem and has physical instability issue عميل يواجه",
        "options": [
            "voice down",
            "Physical instability",
            "noise issue",
        ],
        "correct_answer": "Physical instability",
        "day": "Day - 08 Voice Cases",
    },
    {
        "eng_question": "in voice verification .. After calling CST's on landline number CCA found Record Massage الرقم مرفوع مؤقت من الخدمة  CCA action will be…?",
        "arabic_question": "بعد الاتصال بالخط الارضي للعميل موظف خدمة العملاء وجد رسالة ( الرقم مرفوع مؤقت من الخدمة) ما هو الاجراء المناسب  voice verification اثناء",
        "options": [
            "Consider Voice Down + Create TT Create TT + اعتبار الحرارة فاصلة",
            "Consider Voice Up + Create SR Create SR + اعتبار الحرارة شغالة",
            "Ask CST to pay landline bills اطلب من العميل دفع الفواتير الارضي",
        ],
        "correct_answer": "Consider Voice Down + Create TT Create TT + اعتبار الحرارة فاصلة",
        "day": "Day - 08 Voice Cases",
    },
    {
        "eng_question": "CST Follow voice down ticket after 25 hour from escalating it and ticket still on IU CCA action will be …?",
        "arabic_question": "ا هو الاجراء المناسب  IU  بعد 25 ساعة من تصعيد الشكوى ومازالت موجودة فى قسم voice down ticket عميل بيتابع على",
        "options": [
            "Re-escalate Ticket + create SR ​​FBB Tech Problem---​Voice Down​---​Re-Escalation create SR ​​FBB Tech Problem---​Voice Down​---​Re-Escalation + Ticket اعادة تصعيد"
            "Inform CST Within  SLA +create SR ​​FBB Tech Problem---​Voice Down​---Follow Up create SR ​​FBB Tech Problem---​Voice Down​---Follow Up + اخبار العميل بانه فى خلال المدة",
            "Inform CST Passed SLA + Create IR +create SR ​​FBB Tech Problem---​Voice Down​---Follow Up after SLA Create IR +create SR ​​FBB Tech Problem---​Voice Down​---Follow Up after SLA + اخبار العميل بتجاوز المدة",
        ],
        "correct_answer": "Inform CST Passed SLA + Create IR +create SR ​​FBB Tech Problem---​Voice Down​---Follow Up after SLA Create IR +create SR ​​FBB Tech Problem---​Voice Down​---Follow Up after SLA + اخبار العميل بتجاوز المدة",
        "day": "Day - 08 Voice Cases",
    },
    {
        "eng_question": "CST has problem in Call waiting service CCA action will be ..?",
        "arabic_question": "ماهو الاجراء المناسب Call waiting عميل يواجه مشكلة فى خدمة",
        "options": [
            "Transfer CST to fixed line VDN تحويل العميل لقسم الخط الارضي"
            "Escalate Voice Down Voice Down تصعيد",
            "Inform CST to pay all landline bills اخبار العميل بدفع فواتير الخط الارضي",
        ],
        "correct_answer": "Transfer CST to fixed line VDN تحويل العميل لقسم الخط الارضي",
        "day": "Day - 08 Voice Cases",
    },
    {
        "eng_question": "Customer problem voice not working or out of service after pay bill after cut off and informed that issue started before cutoff date , CCA Right Action",
        "arabic_question": "ما هو الاجراء المناسب cutoff date وابلغنا ان المشكلة بدأت قبل cut off عميل يواجه انقطاع الحرارة او خارج الخدمة بعد دفع الفاتورة بعد",
        "options": [
            "Phone set available step السؤال عن عدة تليفون متاحة",
            "Transfer CST to fixed line Q تحويل العميل الى الخط الارضي",
            "Create UCRM ( RCR Complaint ) UCRM عمل شكوى على",
        ],
        "correct_answer": "Phone set available step السؤال عن عدة تليفون متاحة",
        "day": "Day - 08 Voice Cases",
    },
    {
        "eng_question": "CCA found that CST's landline number has work order رفع نهائي متأخرات أقساط  In Customer Profile Tool ..... CCA action will be…?",
        "arabic_question": "ماهو الاجراء المناسب Customer Profile Tool  موظف خدمة العملاء وجد امر الشغل الخاص بالخط الارضي للعميل ( رفع نهائي متأخرات أقساط)  فى",
        "options": [
            "Inform CST to pay all due installments اخبار العميل دفع الاقساط  المستحقة",
            "Inform CST to pay all landline bills اخبار العميل دفع فواتير الخط الارضي",
            "Follow change phone number process change phone number متابعة اجراءات",
        ],
        "correct_answer": "Inform CST to pay all due installments اخبار العميل دفع الاقساط  المستحقة",
        "day": "Day - 08 Voice Cases",
    },
    {
        "eng_question": "Voice overlapping can happened between?",
        "arabic_question": "يمكن ان تحدث بين Voice overlapping",
        "options": [
            "2 numbers with same government رقمين فى نفس المحافظة",
            "2 numbers in the different  exchange رقمين فى سنترال مختلف",
            "2 numbers in the same exchange رقمين فى نفس السنترال",
        ],
        "correct_answer": "2 numbers in the same exchange رقمين فى نفس السنترال",
        "day": "Day - 08 Voice Cases",
    },
    {
        "eng_question": "CCA must check voice verification before escalating?",
        "arabic_question": ":قبل تصعيد voice verification يجب على موظف خدمة العملاء التأكد من",
        "options": [
            "All physical cases",
            "Data Down only",
            "logical cases",
        ],
        "correct_answer": "All physical cases",
        "day": "Day - 08 Voice Cases",
    },
    {
        "eng_question": "Voice Cases override any physical case?",
        "arabic_question": "؟physical تتجاوز اى مشكلة Voice  مشاكل",
        "options": [
            "True",
            "Flase",
        ],
        "correct_answer": "True",
        "day": "Day - 08 Voice Cases",
    },
    {
        "eng_question": "Voice Down TT SLA is?",
        "arabic_question": "؟ Voice Down المدة المحددة لحل مشكلة",
        "options": [
            "2 Days",
            "1 Days",
            "3 Days",
        ],
        "correct_answer": "1 Days",
        "day": "Day - 08 Voice Cases",
    },
    {
        "eng_question": "If CST has landline bill with 75 LE CCA action will be?",
        "arabic_question": "لو العميل عليه فاتوره ب 75 جنيه, هتعمل ايه يا باشا ؟",
        "options": [
            "Check voice status",
            "Stop troublshoting and inform CST to pay all due bills",
            "Check grace period",
        ],
        "correct_answer": "Check grace period",
        "day": "Day - 08 Voice Cases",
    },
    {
        "eng_question": "If CST is calling from the same landline number that's means?",
        "arabic_question": "لو العميل بيكلمك يا معلم من نفس رقم الارضي, فماذا يعني هذا",
        "options": [
            "CST has landline bill",
            "Voice maybe down",
            "Voice is working fine",
        ],
        "correct_answer": "Voice is working fine",
        "day": "Day - 08 Voice Cases",
    },
    {
        "eng_question": "CST is calling from different landline number and inform us that voice is working CCA action will be ?",
        "arabic_question": "العميل كلمك من رقم ارضي مختلف و قلك ال Voice زي الفل يا صحبي, هتعمل ايه ؟",
        "options": [
            "Consider voice up",
            "Call CST landline number",
            "Should confirm with CST first if tested voice via phone set before call",
        ],
        "correct_answer": "Should confirm with CST first if tested voice via phone set before call",
        "day": "Day - 08 Voice Cases",
    },
    {
        "eng_question": "CST is calling from different landline number and inform us that voice is working but havn't phone set available, CCA action will be?",
        "arabic_question": "العميل كلمك من خط ارضي مختلف و قلك ال Voice شغال تمام بس مفيش عدة ارضي والله, هتعنل ايه ؟",
        "options": [
            "Ask CST to test voice by phone set",
            "Consider Voice Up + Create SR",
            "Put CST on hold and call CST landline number",
        ],
        "correct_answer": "Put CST on hold and call CST landline number",
        "day": "Day - 08 Voice Cases",
    },
    {
        "eng_question": "If we call CST on his ADSL number to check voice status, we find another person respond, your action",
        "arabic_question": "بتكلم العميل عشان تشوف حاله ال Voice رد عليك حد تاني, هتعمل ايه؟ (خلبالك دا كمين)",
        "options": [
            "Consider Voice Up + Create SR",
            "TS Voice overlapping",
            "Confirm landline number",
        ],
        "correct_answer": "Confirm landline number",
        "day": "Day - 08 Voice Cases",
    },
    {
        "eng_question": "CST has data down after checking voice CCA found voice is also down, CCA will escalate?",
        "arabic_question": "العميل ال data عنده down و بعد فحص ال Voice طلع هو كمان down, (افتكر مين ديما بتبقي مع مين) هتصعد ايه؟",
        "options": [
            "Data down",
            "Voice down",
            "Data and Voice Down",
        ],
        "correct_answer": "Data and Voice Down",
        "day": "Day - 08 Voice Cases",
    },
    {
        "eng_question": "Customer Problem Voice not working or out of service after paid his bill after cut off date and CST confirmed that issue started from cut off date?",
        "arabic_question": "العميل عنده voice مش شغال او out of service بعد دفع الفواتير و بعد تاريخ ال Cut Off بعد مع ال agent أكد ان المشكله من تاريخ ال Cut off",
        "options": [
            "Transfer CST to fixed line Q",
            "Phone set available step",
            "Create UCRM (RCR Complain)",
        ],
        "correct_answer": "Create UCRM (RCR Complain)",
        "day": "Day - 08 Voice Cases",
    },
    {
        "eng_question": "Voice not working or out of service and voice problem wasn't due to unpaid landline bills and still exist after paying the bill CCA action will be?",
        "arabic_question": "ال Voice down او out of service و المشكلة مش في الفواتير و المشكله لسا موجوده حتي بعد دفع الفواتير؟",
        "options": [
            "Create UCRM (RCR Complaint)",
            "Transfer CST to fixed line Q",
            "Phone set available step",
        ],
        "correct_answer": "Phone set available step",
        "day": "Day - 08 Voice Cases",
    },
    {
        "eng_question": "The first step of voice verification if CST is not migrated to BSS is",
        "arabic_question": "اول خطوه في ال voice verfication لو العميل مش علي ال BSS",
        "options": [
            "Check CST calling from same ADSL number",
            "Check landline bills",
            "Check voice from main",
        ],
        "correct_answer": "Check landline bills",
        "day": "Day - 08 Voice Cases",
    },
    {
        "eng_question": "Voice verification steps, that's meaning you have to check landline bills and .. ?",
        "arabic_question": "ال voice verification بتشوف فيها الفواتير و ايه .؟",
        "options": [
            "Check noise or weird voice",
            "Check grace period",
            "Check voice status",
        ],
        "correct_answer": "Check voice status",
        "day": "Day - 08 Voice Cases",
    },
    {
        "eng_question": "If CST has Power Failure which of the following you will do with CST",
        "arabic_question": ":ما هي الخطوه اللي هتابعها مع العميل ,, Power Failure في حاله ان العميل عنده",
        "options": [
            "Check with another CPE and not necessary it's original adapter الرئيسي adapter يجرب بروتر تاني وليس من الضروري ان يكون بال",
            "Check with another CPE with it's original adapter الرئيسي adapter يجرب بروتر تاني ولازم   يكون بال",
            "Change the power led in CPE في الروتر power يغير لمبه ال",
        ],
        "correct_answer": "Check with another CPE with it's original adapter الرئيسي adapter يجرب بروتر تاني ولازم   يكون بال",
        "day": "Day - 09 Data Down Cases",
    },
    {
        "eng_question": "If Data Down Case solved  after Cst Connect From Main Wall outlet and you will create TT to Pilot Follow Up Team , way of communication will be",
        "arabic_question": "ما هي طرق التواصل مع العميل ,,  TT to Pilot Follow Up Team اتحلت بعد توصيل العميل من الفيشه الرئيسيه ..  هتعمل Data Down لو مشكله",
        "options": [
            "Call or SMS or Recorded Message مكالمه او رساله او رساله مسجله",
            "Call or SMS مكالمه او رساله",
            "Call only مكالمه فقط",
        ],
        "correct_answer": "Call only مكالمه فقط",
        "day": "Day - 09 Data Down Cases",
    },
    {
        "eng_question": "SLA for pending fixing TE will be:",
        "arabic_question": "pending fixing TE لل SLA  ما هي ال",
        "options": [
            "2 Days",
            "1 Days",
            "3 Days",
        ],
        "correct_answer": "3 Days",
        "day": "Day - 09 Data Down Cases",
    },
    {
        "eng_question": "Cst Calling Us And Informed (ADSL Led Is Down )While  has 3 logs in NST at 7:00 AM ,7:15 AM and 7:30 AM and called us at 1:00 PM at the same day  and informed that he has a problem in his service case will be",
        "arabic_question": "1:00 PM و7:00 والعميل كلمنا الساعه AM ,7:15 AM and 7:30 AM  في NST  علي ال  logs  ويوجد 3 ADSL Is Down العميل بلغن انا لمبه ال في نفس اليوم وبلغنا ان عنده مشكله في الخدمه ,,المشكله سوف تكون",
        "options": [
            "Down Cases",
            "Physical Instability",
            "BLQ",
        ],
        "correct_answer": "Down Cases",
        "day": "Day - 09 Data Down Cases",
    },
    {
        "eng_question": "While T.S Data Down Case With Cst Adsl Led is Stable and line Become Up , CCA Action",
        "arabic_question": ": ما هو الاجراء المناسب ,,Up  اصبحت مستقره والخط اصبح Adsl  مع العميل ,,  و لمبه ال Data Down اثناء اجراء خطوات مشكله ال",
        "options": [
            "Inform CST with solvent هنبلغ العميل بحل المشكله",
            "Escalate to IU IU هنصعد الشكوي لل",
            "Follow Instability troubleshoot Instability  هنتابع خطوات ال",
        ],
        "correct_answer": "Follow Instability troubleshoot Instability  هنتابع خطوات ال",
        "day": "Day - 09 Data Down Cases",
    },
    {
        "eng_question": "Performing SELT test will inform us with",
        "arabic_question": " : بنقدر نعرف من خلاله SELT اجراء اختبار ال",
        "options": [
            "Refresh the line تحديث الخط",
            "Stability of the line استقرار الخط",
            "Distance between exchange or cabin and CPE المسافه بين السنترال او الكابينه وبين الروتر",
        ],
        "correct_answer": "Distance between exchange or cabin and CPE المسافه بين السنترال او الكابينه وبين الروتر",
        "day": "Day - 09 Data Down Cases",
    },
    {
        "eng_question": "If CST has Ticket data down with update (Re-splitted done )  and Cst  connected his CPE From Main Wire Then ,,, CCA Will Inform cst Next Step",
        "arabic_question": "  : والعميل وصل من السلك الرئيسي,,  ما هي الخطوه التاليه update (Re-splitted done ) ويوجد data down في حاله وجود شكوي للعميل",
        "options": [
            "Create TT for internal wiring TT for internal wiring هنصعد",
            "Check availability to test by another CPE  الامكانيه عند العميل انه يجرب بروتر تاني",
            "Escalate to IU IU هنصعد الشكوي لل",
        ],
        "correct_answer": "Check availability to test by another CPE  الامكانيه عند العميل انه يجرب بروتر تاني",
        "day": "Day - 09 Data Down Cases",
    },
    {
        "eng_question": "In Case T.S Data Down Case and Cst has ( MSAN Type: Yes ) you will measure distance with",
        "arabic_question": "  : سوف تحسب المسافه علي ,,  ( MSAN Type: Yes ) و خط العميل  ,,  Data Down في حاله ان العميل عنده مشكله",
        "options": [
            "10 meter",
            "50 meter",
            "150 meter",
        ],
        "correct_answer": "10 meter",
        "day": "Day - 09 Data Down Cases",
    },
    {
        "eng_question": "The time that IU ends work per day is:",
        "arabic_question": " : في اليوم IU  ما هو وقت نهايه عمل قسم ال",
        "options": [
            "10:00 PM",
            "8:00 PM",
            "9:00 PM",
        ],
        "correct_answer": "8:00 PM",
        "day": "Day - 09 Data Down Cases",
    },
    {
        "eng_question": "Escalation Data Down to IU SLA will be:",
        "arabic_question": " IU  لل Data Down عند تصعيد SLA  ما هي ال",
        "options": [
            "2 Days",
            "1 Day",
            "1 Hour",
        ],
        "correct_answer": "1 Day",
        "day": "Day - 09 Data Down Cases",
    },
    {
        "eng_question": "Power Failure means ?",
        "arabic_question": "يعني ايه Power Failure ?",
        "options": [
            "Power led not existed",
            "Power led not working",
            "Power led not working or working with red color",
        ],
        "correct_answer": "Power led not working or working with red color",
        "day": "Day - 09 Data Down Cases",
    },
    {
        "eng_question": "If CST has power failure which of the following you will do with the CST ?",
        "arabic_question": "صحبي لو ال عميل عندو power failure هتعمل معاه ايه ؟",
        "options": [
            "Check with another CPE and not necessary its original adapter",
            "Change the power led in CPE",
            "Check with another CPE with its original adapter",
        ],
        "correct_answer": "Check with another CPE with its original adapter",
        "day": "Day - 09 Data Down Cases",
    },
    {
        "eng_question": "If CST called us informed that he has cut cable you will follow normal troubleshoot in ticket maker",
        "arabic_question": "لو العميل كلمك و قلك عندو قطع هتكمل معاه toubleshoot عادي من ال ticket maker ?",
        "options": [
            "True",
            "False",
        ],
        "correct_answer": "False",
        "day": "Day - 09 Data Down Cases",
    },
    {
        "eng_question": "If customer line in ASSIA no provisioned that means",
        "arabic_question": "لو خط العميل علي ال ASSIA ظاهر not provisioned, دا معناه ايه ؟",
        "options": [
            "CST not supported by ASSIA",
            "CST supported by ASSIA",
            "ASSIA is down",
        ],
        "correct_answer": "CST not supported by ASSIA",
        "day": "Day - 09 Data Down Cases",
    },
    {
        "eng_question": "If CST has data and voice down case after connect from main wall outlet problem solved you will",
        "arabic_question": "لو العميل كان عندو data and voice down بس بعد م وصل main wall outlet المشكله اتحلت",
        "options": [
            "Create TT for internal wiring",
            "Inform CST with solvent",
            "Inform CST to change splitter",
        ],
        "correct_answer": "Create TT for internal wiring",
        "day": "Day - 09 Data Down Cases",
    },
    {
        "eng_question": "If we run SELT and customer's line connected with exchange you will measure distance with",
        "arabic_question": "لو عملت run لل SELT علي خط العميل و العميل متوصل للسنترال هتقيس المسافة ب ايه ؟",
        "options": [
            "10 meters",
            "150 meters",
            "50 meters",
        ],
        "correct_answer": "150 meters",
        "day": "Day - 09 Data Down Cases",
    },
    {
        "eng_question": "If power led is down and CST uses original adapter next step will be",
        "arabic_question": "لو لمبة ال power فصله و العميل بيستخدم ال شاحن الاصلي, هتعمل ايه ؟",
        "options": [
            "Escalate yo IU",
            "Try another wall-plug",
            "Direct CST to CSO",
        ],
        "correct_answer": "Try another wall-plug",
        "day": "Day - 09 Data Down Cases",
    },
    {
        "eng_question": "If CST has data down case and when you checked SELT you found that CST is not supported by ASSIA you will?",
        "arabic_question": "لو العميل عندو data down و لما دخلت علي ال ASSIA لقيتو not supported هتعمل ايه ؟",
        "options": [
            "Escalate to IU",
            "Inform CST to call us again as system down",
            "Check connection type",
        ],
        "correct_answer": "Check connection type",
        "day": "Day - 09 Data Down Cases",
    },
    {
        "eng_question": "SLA for internal wiring TT",
        "arabic_question": "ال SLA بتاع ال internal wiring",
        "options": [
            "2 hours",
            "1 hour",
            "1 day",
        ],
        "correct_answer": "2 hours",
        "day": "Day - 09 Data Down Cases",
    },
    {
        "eng_question": "If CPE restarted automatically and power LED turned off while CPE restarted you will consider it as",
        "arabic_question": "لو الروتر عمل restart automatically و لمبة ال  LED طفت, دا يعتبر ايه",
        "options": [
            "Power Failure",
            "Physical Instability",
            "No Problem",
        ],
        "correct_answer": "Power Failure",
        "day": "Day - 09 Data Down Cases",
    },
    {
        "eng_question": "While follow with cst WACP Case and Cst Line Status is Down and Matrix Status is also Down so the next step is :",
        "arabic_question": "في حالة متابعة خطوات ال WCAP كانت حالة الخط عند العميل :down وع ال Matrix: down , الخطوة التالية هتكون:",
        "options": [
            "Troubleshoot as Data Down نتابع Data Down",
            "Escalate to IU نصعد لل IU",
            " Inform Cst to check his CPE نقول للعميل يفحص الراوتر",
        ],
        "correct_answer": "Troubleshoot as Data Down نتابع Data Down",
        "day": "Day - 10 Wrong Card and Port",
    },
    {
        "eng_question": "In Case CCA will Re-escalate WCAP to IU as a second escalation , So the right SLA is :",
        "arabic_question": "في حالة اننا هنعيد تصعيد ال WCAP للمرة التانية,, ال SLA الصحيحة هتكون",
        "options": [
            "1 Working Day يوم عمل",
            "1 Day يوم",
            "2 Days يومين",
        ],
        "correct_answer": "1 Day يوم",
        "day": "Day - 10 Wrong Card and Port",
    },
    {
        "eng_question": " In case ticket returned with update ( Outside TEData ) , CCA right action according to the customer's case :",
        "arabic_question": "في حالة رجوع الشكوى ب update ( Outside TEData ) . فالاجراء الصحيح على حسب مشكلة العميل هيكون:",
        "options": [
            "will create the below SR ( Broadband>Technical>ADSL/VDSL>CC service Activation>CPE Configuration ) - هنعمل ال SR دى ( Broadband>Technical>ADSL/VDSL>CC service Activation>CPE Configuration )",
            "will create the below SR ( FBB Tech Inquiry>Services>Change Box - No Technical Issue ) - هنعمل ال SR دى ( FBB Tech Inquiry>Services>Change Box - No Technical Issue )",
            "will create the below SR ( Broadband>Technical>ADSL/VDSL>CC service Activation>Global Problem - هنعمل ال SR دى ( Broadband>Technical>ADSL/VDSL>CC service Activation>Global Problem )",
        ],
        "correct_answer": "will create the below SR ( Broadband>Technical>ADSL/VDSL>CC service Activation>CPE Configuration ) - هنعمل ال SR دى ( Broadband>Technical>ADSL/VDSL>CC service Activation>CPE Configuration )",
        "day": "Day - 10 Wrong Card and Port",
    },
    {
        "eng_question": "In case the ticket returned with updated CPE problem close code 74  , Cst from Cairo and insist to check with another available CPE , CCA right action is",
        "arabic_question": "في حالة ان الشكوى رجعت ب updated CPE problem close code 74  , والعميل من القاهرة واصر انه يجرب براوتر تانى , الاجراء الصحيح هيكون:",
        "options": [
            "will inform the Customer that he can check with another CPE normally - نقول للعميل انه يقدر يجرب براوتر تانى عادى",
            "will inform the customer that he should check the CPE on CSO Mandatory - ضرورى اننا نقول للعميل انه يفحص الراوتر فى الفرع",
        ],
        "correct_answer": "will inform the customer that he should check the CPE on CSO Mandatory - ضرورى اننا نقول للعميل انه يفحص الراوتر فى الفرع",
        "day": "Day - 10 Wrong Card and Port",
    },
    {
        "eng_question": "In case WCAP CST disconnect phone cable from CPE and ADSL still UP , It is CPE Problem :",
        "arabic_question": "في حالة ال WCAP , العميل قام بفصل كابل الحرارة من الراوتر ولكن لمبة ال DSL مازالت up , هتكون كده مشكلة راوتر",
        "options": [
            "True",
            "False",
        ],
        "correct_answer": "True",
        "day": "Day - 10 Wrong Card and Port",
    },
    {
        "eng_question": "Cst has Ticket Data Down with Update ( Close Code (82): External problem- cable maintenance needed ) , So CCA will Inform cst  SLA :",
        "arabic_question": "شكوى data down وعليها Update ( Close Code (82): External problem- cable maintenance needed )  , هنقول للعميل SLA :",
        "options": [
            "2 Day - يومين",
            " No estimated time - مفيش وقت محدد",
            "Case escalated to the responsible team and we are waiting for their update with 3 days SLA - الشكوى اتصعدت للقسم المختص بيها واحنا منتظرين الرد منهم وهيكون خلال 3 ايام",
        ],
        "correct_answer": "Case escalated to the responsible team and we are waiting for their update with 3 days SLA - الشكوى اتصعدت للقسم المختص بيها واحنا منتظرين الرد منهم وهيكون خلال 3 ايام",
        "day": "Day - 10 Wrong Card and Port",
    },
    {
        "eng_question": "In wrong card and port or disable lines, CCA shouldn't search on Matrix using ADSL & customer account no. to avoid any indeterminate for duplicated matrix :",
        "arabic_question": "فى حالة ال WCAP او الline Disabled ,, ال CCA مش لازم يعمل بحث على ال matrix باستخدام الرقم الارضى و CST Account , لتجنب اى خطأ زى ال Duplicated matrix",
        "options": [
            "True",
            "False",
        ],
        "correct_answer": "False",
        "day": "Day - 10 Wrong Card and Port",
    },
    {
        "eng_question": "If the Customer number belongs to Hayah Karima project and cst has Major Fault with no estimated time , SLA will be :",
        "arabic_question": "لو خط العميل ينتمى لمشروع حياة كريمة وفيه Major fault problem من غير وقت محدد فال SLA اللى هنقولها للعميل هتكون:",
        "options": [
            "3 working days - 3 ايام عمل",
            "3 ايام عمل - 3ايام",
            "5 Days - 5 ايام",
        ],
        "correct_answer": "5 Days - 5 ايام",
        "day": "Day - 10 Wrong Card and Port",
    },
    {
        "eng_question": " In case CCA follow WCAP case and Cst  Line Status from main : Down and Matrix : UP, No have Logs , So CCA right action :",
        "arabic_question": "في حالة متابعة ال WCAP مع العميل كانت حالة الخط عنده: down وع ال matrix: up ولا يوجد logs ,, الاجراء الصحيح هيكون:",
        "options": [
            "Direct the customer to CSO to check the CPE - نوجه العميل للفرع عشان يفحص الراوتر",
            "Should reset & configure - لازم نعمل Reset& configure",
            " Escalate to IU - نصعد لل IU",
        ],
        "correct_answer": " Escalate to IU - نصعد لل IU",
        "day": "Day - 10 Wrong Card and Port",
    },
    {
        "eng_question": "customer which has Major Fault update with no estimated time should follow on his case with us :",
        "arabic_question": "العميل اللى عنده Major fault problem بدون وقت محدد هو اللى بيتابع معانا على الشكوى",
        "options": [
            "True",
            "False",
        ],
        "correct_answer": "True",
        "day": "Day - 10 Wrong Card and Port",
    },
    {
        "eng_question": "while follow with CST WCAP case and CST line status is down and matrix is UP, so the next step is",
        "arabic_question": "و انت بتابع مع العميل في حالة WCAP و حالة خط العميل Down و ال matrix up ايه الخطوه الجيه ؟",
        "options": [
            "Follow Data status from main step",
            "Check Log IP Step",
            "Escalate to IU",
        ],
        "correct_answer": "Follow Data status from main step",
        "day": "Day - 10 Wrong Card and Port",
    },
    {
        "eng_question": "Customer Follow Up escalated ticket (Wrong Card and Port) and the TKT still within SLA, So right SR is",
        "arabic_question": "العميل بيعمل follow up لحالة Wrong card and port و ال ticket ليسا في فتره ال SLA",
        "options": [
            "FBB Tech Problem > Wrong card and port > Follow up",
            "FBB Tech Problem > Wrong card and port > Re Escalation",
            "FBB Tech Problem > Wrong card and port > Follow up afte SLA",
        ],
        "correct_answer": "FBB Tech Problem > Wrong card and port > Follow up",
        "day": "Day - 10 Wrong Card and Port",
    },
    {
        "eng_question": "CCA should not stop escalation to IU due to any reason while making rest & configuration such as CPE page can't be accessed",
        "arabic_question": "ال agent مش مفروض يوقف عملية ال escalation لأي سبب من الاسباب اثناء عمل reset & configuration زي مثلا ان صفحة الروتر مش بتخش",
        "options": [
            "True",
            "False",
        ],
        "correct_answer": "True",
        "day": "Day - 10 Wrong Card and Port",
    },
    {
        "eng_question": "CST has ticket WCAP in IU pool and TKT passed SLA, so CCA will inform CSA SLA",
        "arabic_question": "العميل عندو ticket في IU pool, و ال TKT عديت فتره ال SLA هتبلغ العميل ايه ؟,",
        "options": [
            "1 Working day",
            "1 Day",
            "2 Days",
        ],
        "correct_answer": "1 Day",
        "day": "Day - 10 Wrong Card and Port",
    },
    {
        "eng_question": "Its not mandatory to ask customer for 2 mobiles numbers while escalating any physical case",
        "arabic_question": "مش ضروري تسأل العميل علي رقمين تلفون في اي physical case",
        "options": [
            "True",
            "False",
        ],
        "correct_answer": "False",
        "day": "Day - 10 Wrong Card and Port",
    },
    {
        "eng_question": "In case WCAP CSE disconnected phone cable from CPE and ADSL still up, is it CPE problem ?",
        "arabic_question": "لو عميل WCAP فصل كبل التلفون من ال CPE و لمبة ال ADSL ليسه UP, المشكله في ال CPE?",
        "options": [
            "True",
            "False",
        ],
        "correct_answer": "True",
        "day": "Day - 10 Wrong Card and Port",
    },
    {
        "eng_question": "Customer Follow up his ticket (Wrong Card and Port) And the TKT has update Major Fault within First SLA, so right SR",
        "arabic_question": "العميل بيتايع ticket WCAP و ال ticket نزلها update major fault في اول SLA, هنعمل انهي SR",
        "options": [
            "FBB Tech Problem > Wrong Card and port > Major Fault",
            "FBB Tech Problem > Wrong Card and port > Major Fault After SLA",
            "FBB Tech Problem > Wrong Card and port > Major Fault within SLA",
        ],
        "correct_answer": "FBB Tech Problem > Wrong Card and port > Major Fault within SLA",
        "day": "Day - 10 Wrong Card and Port",
    },
    {
        "eng_question": "CST has ticker update (Abuser as per TE) and customer said that issue covered, so CCA right action is",
        "arabic_question": "العميل عندو update (Abuser as per TE) و العميل بيقول المشكله اتحلت",
        "options": [
            "Escalate Normaly",
            "Inform customer to check with his exchange first",
            "Transfer CST to fixed Line VDN",
        ],
        "correct_answer": "Escalate Normaly",
        "day": "Day - 10 Wrong Card and Port",
    },
    {
        "eng_question": "Customer follow up his ticket (WCAP) and the TKT has update Major Fault Passed SLA and still in the same update afte RE-Escalation TKT, so right SR",
        "arabic_question": "العميل بيعمل follow up علي ticket WCAP و ال ticket نزلها update Major Fault و ليسا في نفس ال Update يعد ال RE-Escalation",
        "options": [
            "FBB Tech Problem > Wrong Card and port > Major Fault",
            "FBB Tech Problem > Wrong Card and port > Major Fault After SLA",
            "FBB Tech Problem > Wrong Card and port > Major Fault within SLA",
        ],
        "correct_answer": "FBB Tech Problem > Wrong Card and port > Major Fault After SLA",
        "day": "Day - 10 Wrong Card and Port",
    },
    {
        "eng_question": "CST has ticket data down with update (Morkzat), so CCA will inform CST with SLA",
        "arabic_question": "Ticket العميل فيها update (Morkzar) هنبلغ العميل ب SLA ايه",
        "options": [
            "2 Days",
            "No Estimated time",
            "3 Days",
        ],
        "correct_answer": "3 Days",
        "day": "Day - 10 Wrong Card and Port",
    },
    {
        "eng_question": "If there 5 logs exist during last 12 hours with 1 log during last 3 hours  . Handle as ?",
        "arabic_question": "لو العميل عنده 5 logs في خلال اخر 12 hours منهم 1 log  في اخر 3 hours . هتتابع مع العميل ايه ؟",
        "options": [
            "Data down",
            "Physical Instability",
            "Logical Instability",
        ],
        "correct_answer": "Physical Instability",
        "day": "Day - 11 Physical Instability",
    },
    {
        "eng_question": "while troubleshooting physical instability ,CCA found Landline bills is 80 LE and passed the grace period , CCA stop troubleshooting and inform CST that he has to pay his bills first, right SR is ",
        "arabic_question": "واحنا بنتابع خطوات ال physical instability   , ال CCA وجد ان العميل عليه فاتوره قيمتها 80 جنيه وعدت فتره السماح , الCCA هيوقف كل الخطوات وهيبلغ العميل انه محتاج يدفع الفاتوره أولا , ال SR المناسبه",
        "options": [
            "FBB Tech Problem > ​​Physical Instability > ​Follow Up",
            "FBB Tech Problem > ​​Physical Instability >TE-Billing",
            "FBB Tech Problem >​ Physical Instability > CPE Problem",
        ],
        "correct_answer": "FBB Tech Problem > ​​Physical Instability >TE-Billing",
        "day": "Day - 11 Physical Instability",
    },
    {
        "eng_question": "Time Frame For Physical Instability  Case :",
        "arabic_question": "ال Time frame في حاله ال physical instability :",
        "options": [
            "1 day",
            "2 days",
            "5 days",
        ],
        "correct_answer": "5 days",
        "day": "Day - 11 Physical Instability",
    },
    {
        "eng_question": "while troubleshooting physical instability , Clear View Result After Search No DSL Physical Layer is detected ,next action is :",
        "arabic_question": "واحنا بنتابع خطوات ال physical instability ,نتيجه ال clear view بعد ال search كانت no dsl physical layer is detected , الخطوه التاليه :",
        "options": [
            "Check connection type - هنفحص نظام التوصيل",
            "Check last fix date according to TTS and customer input at same time - هنشوف اخر اصلاح تم من جانب ال TTS ومن جانب العميل",
        ],
        "correct_answer": "Check last fix date according to TTS and customer input at same time - هنشوف اخر اصلاح تم من جانب ال TTS ومن جانب العميل",
        "day": "Day - 11 Physical Instability",
    },
    {
        "eng_question": "Before escalating Physical Instability Case , should be check Voice Verification  ?",
        "arabic_question": "قبل تصعيد شكوي physical instability , لازم نتابع خطوات ال voice verification ؟",
        "options": [
            "True",
            "False",
        ],
        "correct_answer": "True",
        "day": "Day - 11 Physical Instability",
    },
    {
        "eng_question": "While troubleshooting physical instability, After run clear view result is : Run Real Time Profile Optimization , right action is :",
        "arabic_question": "واحنا بنتابع خطوات ال physical instability , بعد ما عملنا ال clear view النتيجه كانت run real time profile optimization , التصرف الصح :",
        "options": [
            "check connection - هنفحص التوصيلات",
            "Check Voice Verification then Escalate to IU - هنتابع خطوات ال voice verification ثم نصعد لل IU",
        ],
        "correct_answer": "Check Voice Verification then Escalate to IU - هنتابع خطوات ال voice verification ثم نصعد لل IU",
        "day": "Day - 11 Physical Instability",
    },
    {
        "eng_question": "SLA for Physical Instability Contradiction Case  ?",
        "arabic_question": "ما هي ال SLA الخاصه بشكوي ال physical instability contradiction ؟",
        "options": [
            "1 D",
            "2 H",
        ],
        "correct_answer": "2 H",
        "day": "Day - 11 Physical Instability",
    },
    {
        "eng_question": "Physical Instability will be escalated to :",
        "arabic_question": " ال physical instability بتتصعد لمين :",
        "options": [
            "IU",
            "NOC",
            "SLS",
        ],
        "correct_answer": "IU",
        "day": "Day - 11 Physical Instability",
    },
    {
        "eng_question": "CST has Physical Instability ticket in your pool , and problem still the same , after troubleshooting , CCA will ​​Re Escalate ticket again to IU ,, right SR is :",
        "arabic_question": "العميل عنده شكوي physical instability وموجوده عندنا فال pool , والمشكله لسه موجوده متحلتش ,وبعد اتباع الخطوات , ال CCA هيصعد الشكوي تاني الي ال IU , ال SR المناسبه :",
        "options": [
            "FBB Tech Problem > ​​Physical Instability > ​Follow Up",
            "FBB Tech Problem > ​​Physical Instability > ​​Re Escalation",
            "FBB Tech Problem > ​​Physical Instability > ​Follow up After SLA",
        ],
        "correct_answer": "FBB Tech Problem > ​​Physical Instability > ​​Re Escalation",
        "day": "Day - 11 Physical Instability",
    },
    {
        "eng_question": "while troubleshooting Physical Instability, CCA found voice is down ,  ticket will escalated as :",
        "arabic_question": "واحنا بنتابع خطوات ال physical instability ال CCA وجد ان الحراره مش شغاله , الشكوي اللي هتتصعد هتكون :",
        "options": [
            "Physical Instabilitغ",
            "Voice Down",
        ],
        "correct_answer": "Voice Down",
        "day": "Day - 11 Physical Instability",
    },
    {
        "eng_question": "While Escalating Physical Instability Case to IU, SLA will be",
        "arabic_question": "و انت بتصعد physical instability لل IU ال SLA بتكون",
        "options": [
            "1 Day",
            "2 Day",
            "5 Day",
        ],
        "correct_answer": "1 Day",
        "day": "Day - 11 Physical Instability",
    },
    {
        "eng_question": "Customer has ticket physical instability in IU, CCA informed him that he within SLA, Right SR is",
        "arabic_question": "ال SR الهتعملها لو العميل كلمك و عندو physical instability في ال IU وليسا within SLA",
        "options": [
            "FBB Tech Problem > Physical Instability > Follow up after SLA",
            "FBB Tech Problem > Physical Instability > Follow up",
            "FBB Tech Problem > Physical Instability Contradiction > Follow up",
        ],
        "correct_answer": "FBB Tech Problem > Physical Instability > Follow up",
        "day": "Day - 11 Physical Instability",
    },
    {
        "eng_question": "While escalating Physical Instability CCA must inform customer to keep his CPE on",
        "arabic_question": "و انت بتصعد شكوة للعميل physical instability لازن تقله يسيب ال router شغال",
        "options": [
            "True",
            "False",
        ],
        "correct_answer": "True",
        "day": "Day - 11 Physical Instability",
    },
    {
        "eng_question": "CCA must ask customer for 2 mobile numbers while escalating physical instability case",
        "arabic_question": "لازن تسأل العميل عن 2 رقم موبيل و انت بتصعد Physical instability",
        "options": [
            "True",
            "False",
        ],
        "correct_answer": "True",
        "day": "Day - 11 Physical Instability",
    },
    {
        "eng_question": "CCA must inform cutomer with ticket number while escalating physical instability case",
        "arabic_question": "لازم تقول رقم الشكوه وانت بتصعد Physical instability",
        "options": [
            "True",
            "False",
        ],
        "correct_answer": "True",
        "day": "Day - 11 Physical Instability",
    },
    {
        "eng_question": "In Physical instability case we will escalate the ticket to (Pilot Follow up) when problem solved after CST connected from main outlet",
        "arabic_question": "لازم نصعد ticket لفريق ال pilot follow up لما المشكله تتحل بعد التوصيل من فيشة رئيسية",
        "options": [
            "True",
            "False",
        ],
        "correct_answer": "True",
        "day": "Day - 11 Physical Instability",
    },
    {
        "eng_question": "While troubleshooting physical instability, Clear view result after search technical dispatch is recommended, next action is",
        "arabic_question": "و انت بتعمل troubleshooting ل physical instability ناتج ال clear view after serach كان technical dispatch is recommended هعمل ايه",
        "options": [
            "Check Connection type",
            "Check last fix date according to TTS and customer input at same time",
        ],
        "correct_answer": "Check Connection type",
        "day": "Day - 11 Physical Instability",
    },
    {
        "eng_question": "While Escalating Physical Instability Case to IU for third time, SLA will be",
        "arabic_question": "و انت بتصعد physical instability لل IU للمره الثالثة ال SLA هتكون",
        "options": [
            "1 Day",
            "2 Days",
            "2 Working days",
        ],
        "correct_answer": "1 Day",
        "day": "Day - 11 Physical Instability",
    },
    {
        "eng_question": "While troubleshooting physical instability, connection type: wall outlit, the next step",
        "arabic_question": "اي الخطوه البعد ال Connection type و انت بتعمل troubleshoot ل physical instability من فيشة في الحيطه",
        "options": [
            "Check if connection right or Wrong",
            "Check Splitter esistence before CPE",
        ],
        "correct_answer": "Check if connection right or Wrong",
        "day": "Day - 11 Physical Instability",
    },
    {
        "eng_question": "While troubleshooting physical instability, connection type: wall outlit, Connection is right",
        "arabic_question": "اي الخطوه البعد ال Connection type و انت بتعمل troubleshoot ل physical instability من فيشة في الحيطه و التوصيل صح",
        "options": [
            "Re Run ASSIA Clear View",
            "Check Splitter esistence before CPE",
        ],
        "correct_answer": "Check Splitter esistence before CPE",
        "day": "Day - 11 Physical Instability",
    },
    {
        "eng_question": "CST has BLQ Case, Customer operational speed is 12 Mb after make selt result was 800 M so you will",
        "arabic_question": "العميل عنده BLQ ,السرعه الفعليه 12 ميجا وبعد ما شغلنا ال selt النتيجه كانت 800 متر , هتعمل ايه",
        "options": [
            "Inform Customer that it is the most suitable speed and follow slowness case is still complain from speed - هبلغ العميل ان ديه السرعه المناسبه وهنتابع معاه slowness لو لسه بيشتكي من السرعه",
            "Follow voice verification then escalate BLQ - هنتابع خطوات ال voice verification ثم نصعد BLQ",
            "Escalate Need Optimization case - هنصعد need optimization",
        ],
        "correct_answer": "Follow voice verification then escalate BLQ - هنتابع خطوات ال voice verification ثم نصعد BLQ",
        "day": "Day - 12 Bad Line Quality",
    },
    {
        "eng_question": "While TS BLQ case and CCA Check Line stability from line details from Assia and found that customer's line is Unstable so the next step is :",
        "arabic_question": "واحنا بنتابع خطوات ال BLQ وال CCA فحص استقرار الخط من line details من ال ASSIA ووجد ان الخط UNSTABLE , الخطوه التايه :",
        "options": [
            "Inform Customer to wait 3 days until tests done on the line - هبلغ العميل انه يستني 3 أيام عشان فيه بعض الفحوصات بتم علي خطه",
            "Escalate Ticket to IU - هنصعد الشكوي للIU",
            "Handle as slowness case - تابع مع العميل مشكله Slowness",
        ],
        "correct_answer": "Inform Customer to wait 3 days until tests done on the line - هبلغ العميل انه يستني 3 أيام عشان فيه بعض الفحوصات بتم علي خطه",
        "day": "Day - 12 Bad Line Quality",
    },
    {
        "eng_question": "CCA should check voice verification before Escalate BLQ case to confirm on voice status :",
        "arabic_question": "ال CCA يجب ان يتابع خطوات ال voice verification قبل تصعيد شكوي blq للتاكد من حاله الحراره :",
        "options": [
            "True",
            "False",
        ],
        "correct_answer": "True",
        "day": "Day - 12 Bad Line Quality",
    },
    {
        "eng_question": "In case escalation of Need Optimization case ask customer to leave the CPE power turned on",
        "arabic_question": "في حاله تصعيد ال need optimization هبلغ العميل انه يسيب الراوتر شغال فالكهربا",
        "options": [
            "True",
            "False",
        ],
        "correct_answer": "True",
        "day": "Day - 12 Bad Line Quality",
    },
    {
        "eng_question": "In Case Ticket BLQ have Update ( Main wire changed ) and Cst still have the same problem, noting that line Supported by ASSIA and no change in the connection setup after our technician visit’s, so the right action is :",
        "arabic_question": "في حاله وجود شكوي BLQ موجود عليها update (main wire changed) والعميل لسه عنده نفس المشكله ,وال ASSIA بتدعم الخط ,ومفيش أي تغيير فالتوصيلات بعد الزياره الفنيه , التصرف الصحيح :",
        "options": [
            "Re-Run the appropriate mode of Clear View - هنعمل اعاده تشغيل لل clear view باختيار mode المناسب",
            "Re-Escalate the Ticket Direct to IU - هنعمل اعاده تصعيد الشكوي للIU مباشرا",
            "Re-Troubleshoot as BLQ - هنعيد خطوات ال BLQ",
        ],
        "correct_answer": "Re-Run the appropriate mode of Clear View - هنعمل اعاده تشغيل لل clear view باختيار mode المناسب",
        "day": "Day - 12 Bad Line Quality",
    },
    {
        "eng_question": "it's not mandatory to take screenshots from selected Clear View mode and its result",
        "arabic_question": "غير الزامي اننا ناخد screenshots من ال clear view mode ومن النتيجه",
        "options": [
            "True",
            "False",
        ],
        "correct_answer": "True",
        "day": "Day - 12 Bad Line Quality",
    },
    {
        "eng_question": " If Customer complaint within TS BLQ case from Bad Box issue , the right SR is :",
        "arabic_question": "لو العميل اشتكي خلال متابعه خطوات ال BLQ من ان البوكس حالته سيئه , ال SR المناسبه :",
        "options": [
            "FBB Tech Problem > BLQ > Other",
            "FBB Tech Problem > BLQ > Bad Box",
            "FBB Tech Problem > BLQ > Ganzara Box",
        ],
        "correct_answer": "FBB Tech Problem > BLQ > Bad Box",
        "day": "Day - 12 Bad Line Quality",
    },
    {
        "eng_question": "Need Optimization case will Escalate to :",
        "arabic_question": "ال need optimization هيتم تصعيدها ل",
        "options": [
            "second level",
            "IU Maintenace",
            "Pilot-SLS",
        ],
        "correct_answer": "Pilot-SLS",
        "day": "Day - 12 Bad Line Quality",
    },
    {
        "eng_question": "CST has BLQ ,line supported by ASSIA clear view after search Technician Dispatch is recommended the next step will :",
        "arabic_question": "العميل عنده blq , ال ASSIA تدعم الخط , ال clear view بعد ال search كانت technician dispatch is recommended , الخطوه التاليه :",
        "options": [
            "Check connection type - هنفحص نوع  التوصيلات",
            "inform CSt connect from main - هبلغ العميل انه يوصل الخط  من الرئيسي",
            "Run Real-time Analysis - هنشغل ال real-time analysis",
        ],
        "correct_answer": "Check connection type - هنفحص نوع  التوصيلات",
        "day": "Day - 12 Bad Line Quality",
    },
    {
        "eng_question": "CST has ASSIA output: Line is out of sync, CCA action as first step:",
        "arabic_question": "خط العميل علي ال ASSIA : line is out of sync ,ال CCA اول خطوه هيعملها :",
        "options": [
            "Escalate to IU - هنصعد الشكوي للIU",
            "Ask CST to connect from main wire - هبلغ العميل انه يوصل الخط  من الكابل الرئيسي",
            "Ensure that the CPE is on - هنتاكد ان الراوتر شغال",
        ],
        "correct_answer": "Ensure that the CPE is on - هنتاكد ان الراوتر شغال",
        "day": "Day - 12 Bad Line Quality",
    },
    {
        "eng_question": "ASSIA clear view result is, No immediate action is recommended, you action is?",
        "arabic_question": "ال Clear view علي ال ASSIA بيديك No immediate action is recommended, هتعمل ايه",
        "options": [
            "Escalate to IU",
            "Inform customer to wait 3 days until tests done one the line (Inform customer to leave CPE on during 3 days)",
            "Connect from main",
        ],
        "correct_answer": "Inform customer to wait 3 days until tests done one the line (Inform customer to leave CPE on during 3 days)",
        "day": "Day - 12 Bad Line Quality",
    },
    {
        "eng_question": "We should infrom CST to leave CPE turned on while escalating BLQ case",
        "arabic_question": "المفروص نبلغ العميل يسيب ال CPE شغال خلال تصعيد شكوه BLQ",
        "options": [
            "True",
            "False",
        ],
        "correct_answer": "True",
        "day": "Day - 12 Bad Line Quality",
    },
    {
        "eng_question": "Line code is must set to ADSL2+ or VDSL according to CST port",
        "arabic_question": "يجب اضافة ال Line code ل ADSL2+ و ال VDSL عند port العميل",
        "options": [
            "True",
            "False",
        ],
        "correct_answer": "True",
        "day": "Day - 12 Bad Line Quality",
    },
    {
        "eng_question": "Line Code for ADSL2+ is",
        "arabic_question": "ال line code بتاع ال ADSL+2",
        "options": [
            "G-992-5",
            "G-922-2",
            "G-992-3",
        ],
        "correct_answer": "G-992-5",
        "day": "Day - 12 Bad Line Quality",
    },
    {
        "eng_question": "CST has ticket in IU pool and passed SLA so you will",
        "arabic_question": "عميل عندو ticket في ال IU وعدى ال SLA",
        "options": [
            "Create delay ticket and inform CST SLA with 2 days",
            "Create delay ticket and inform CST sla with 1 day",
            "Inform CST wait follow up call",
        ],
        "correct_answer": "Create delay ticket and inform CST sla with 1 day",
        "day": "Day - 12 Bad Line Quality",
    },
    {
        "eng_question": "CST has ticket need optimization escalated in 10:00 PM and CST calling at 11:30 PM in same day so you will",
        "arabic_question": "العميل عندو شكوه need optimization متصعده من الساعة 10:00 بليل و العميل بيكلمك الساعة 11:30 بليل",
        "options": [
            "Create delay ticket and inform CST 1 hour",
            "Inform CST waiting follow up call",
            "Inform CST waiting SLA",
        ],
        "correct_answer": "Inform CST waiting SLA",
        "day": "Day - 12 Bad Line Quality",
    },
    {
        "eng_question": "CST has BLQ ticket with update (Working from exchange) without a visit update, right action is",
        "arabic_question": "العميل عندو شكوه BLQ و نزلها Update wokring from exchange without a visit هتعمل ايه",
        "options": [
            "Re-Troubleshoot BLQ",
            "Inform CST that the problem solved",
            "Re-escalate case to IU pool",
        ],
        "correct_answer": "Re-escalate case to IU pool",
        "day": "Day - 12 Bad Line Quality",
    },
    {
        "eng_question": "In BLQ case clear view reults after search is (Technical dispatch is recommended), and after running appropriate mode of Clear View result become (No DSL physical layer is detected), right action is",
        "arabic_question": "في حالة ال BLQ ناتج ال clear view after search كان (Technical dispatch is recommended) بعد معملت الخطوات الازمه ناتج ال Clear view بقي (No DSL Physical layer detected)",
        "options": [
            "Escalate to IU",
            "Inform CST check with another CPE",
            "Check Diagnostic tab in line details",
        ],
        "correct_answer": "Check Diagnostic tab in line details",
        "day": "Day - 12 Bad Line Quality",
    },
    {
        "eng_question": "Second time escalation SLA in BLQ case is",
        "arabic_question": " ال SLA في تصعيد ال BLQ للمره الثانية",
        "options": [
            "2 Day",
            "1 Day",
            "2 Hour",
        ],
        "correct_answer": "1 Day",
        "day": "Day - 12 Bad Line Quality",
    },
    {
        "eng_question": "If customer has ADSL package, VSDL CPE and port is ADSL, CCA should follow change offering process to change the port from ADSL to VDSL in addition to handling the main case BLQ",
        "arabic_question": "لو العميل مشترك في باقة ADSL, روتر VDSL و ال port  ADSL, هتمشي معاه خطوات التحويل من ADSL الى VDSL مع حل مشكله ال BLQ",
        "options": [
            "True",
            "False",
        ],
        "correct_answer": "True",
        "day": "Day - 12 Bad Line Quality",
    },
]
